### PR TITLE
add rspec runtime profiling and .travis.yml linting

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
Related to discussion in #503

**Comment by jhoblitt** [comment]
@rtyler / @petems This may be the smoking gun:

https://travis-ci.org/jenkinsci/puppet-jenkins/jobs/113456469#L1721-L1722

**Comment by rtyler** [comment]
y so slow!

**Comment by rtyler** [comment]
:+1: on this PR though

**Comment by jhoblitt** [comment]
@rtyler thank you - I've opened #517 so the bug isn't only mentioned on closed issues...

**Pull request merged**
