### PR TITLE
update travis test matrix

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by rtyler** [comment]
```
  Debug: hiera(): Cannot find datafile /etc/puppetlabs/code/environments/production/hieradata/common.yaml, skipping
  Debug: Performing a hiera indirector lookup of jenkins::group with options {:variables=>Scope(Class[Jenkins]), :merge=>#<Puppet::Pops::FirstFoundStrategy:0x000000011803c0 @options_t=#<Puppet::Pops::Types::PStructType:0x000000037a6ce8 @elements=[#<Puppet::Pops::Types::PStructElement:0x000000037a6d10 @key_type=#<Puppet::Pops::Types::POptionalType:0x000000037a6d38 @type=#<Puppet::Pops::Types::PStringType:0x000000037a6d88 @size_type=nil, @values=["strategy"]>>, @value_type=#<Puppet::Pops::Types::POptionalType:0x000000037a6ef0 @type=#<Puppet::Pops::Types::PPatternType:0x000000037a6f40 @patterns=[#<Puppet::Pops::Types::PRegexpType:0x000000037a70a8 @pattern="first", @regexp=/first/>]>>>]>, @options={}>}
  Debug: hiera(): Looking up jenkins::group in YAML backend


The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
```

Womp womp. It looks like some Puppet tests have `DEBUG` as their log level and are failing things.

**Comment by jhoblitt** [comment]
We can revert that.  I believe I enabled it trying to figure out why travis runs were timing out in the first place...

**Comment by rtyler** [comment]
@jhoblitt want to do that in this PR or a followup?

**Comment by jhoblitt** [comment]
I'll update the PR

**Comment by jhoblitt** [comment]
😢 I will fix it again.

**Comment by jhoblitt** [comment]
ugh.  Why isn't the travis exclusion working?

**Pull request merged**
