### PR TITLE
(RFC - not ready for merge) use camptocamp/archive for all downloads

### PR DESCRIPTION
**Pull request by jhoblitt**
Replaces direct usage of wget from exec and nanliu/staging.  Intended to be an
interim solution until nanliu/archive gains proxy support.

### CODE REVIEW

**Comment by jhoblitt** [comment]
This PR is in response to discussion in PR #336 about converging on a single method of downloading files.  I've considered a few different modules and the tl;dr is that I'm proposing to exclusively use `camptocamp/archive` until `nanliu/archive` gains proxy support.

I try to use supported/approved modules when possible on the theory that they are less likely to cause an environment conflict.  AFAIK, there are two blessed, popular, and API stable download modules for posix like systems.  `nanliu/staging` & ` maestrodev/wget`.  The former does not have proxy or checksum support.  The later has both but proxy support is only via facts/top level variables. Neither appear to be an ideal fit.

I suspect that `nanliu/archive`, being a native type implementation, is "the future" for downloading files. However, it currently lacks proxy support and presently requires a fair number of gems to be installed on the agent . `camptocamp/archive` has all of the features this module desires but I dislike that the destination filename is implicit based on the resource name, that it creates a file resource for the downloaded file only upon `ensure => absent`, and that the module name conflicts with `nanliu/archive`.

**Comment by rtyler** [comment]
@jhoblitt in general I really like this change, the failing tests concern me though. I might take a whack at fixing it later today if I don't run out of steam first

**Comment by jhoblitt** [comment]
@rtyler Ping me if you don't get to it and I'll try to take a stab and fixing up the tests tomorrow.

**Comment by rtyler** [comment]
@jhoblitt I definitely didn't get to this :P

**Comment by jhoblitt** [comment]
I think the rough consensus is to switch to puppet-community/puppet-archive, so I'm going to retract this PR.

**Pull request closed without merging**
