### PR TITLE
adding service_provider for EL7 for jenkins-slave service

### PR DESCRIPTION
**Pull request by alvin-huang**
For consistency sake, if we are using service_provider for the `jenkins` master service, we should probably add the ability to use it for the `jenkins-slave` service on the slaves as well.

### CODE REVIEW

**Comment by jhoblitt** [comment]
Does this resolve an issue you are experiencing?  The service_provider nonsense came about due to a core puppet problem that should be resolved for puppet > 4.5.

**Comment by alvin-huang** [comment]
IIRC--On CentOS7 boxes, the module drops a systemv init script for the jenkins-slave service and you either need to reload systemd or tell Puppet to treat it like it would for CentOS6 (by the provider).

**Comment by alvin-huang** [comment]
Upon review of #692 that probably solves this issue...

**Comment by jhoblitt** [comment]
@alvin-huang That is good news.  #692 isn't quite ready yet but I hope to merge it today.

**Pull request closed without merging**
