### PR TITLE
Fix syntax for class load of hudson.tasks.Mailer$UserProperty

### PR DESCRIPTION
**Pull request by alan-schwarzenberger**
Fix for #633

### CODE REVIEW

**Comment by alan-schwarzenberger** [comment]
Looks to us as if the test failure is not related to this change. @jhoblitt can you confirm that is the case please?

**Comment by jhoblitt** [comment]
Not sure what happened there.  I've restarted the travis build.

**Comment by trcdabuildserver** [comment]
Thanks, hoping you can accept this PR for the next release.

**Comment by alan-schwarzenberger** [comment]
Thanks, hoping you can accept this PR for the next release.

**Comment by jhoblitt** [comment]
Travis passed!  Thank you for working on this!

**Comment by alan-schwarzenberger** [comment]
Thanks to two of my colleagues in Thomson Reuters who did most of the work on this https://github.com/ekkaphoom and https://github.com/phongsiri-tr (see #633)

**Pull request merged**
