### PR TITLE
initial puppet strings doc format conversion

### PR DESCRIPTION
**Pull request by jhoblitt**
related to #394

### CODE REVIEW

**Comment by jhoblitt** [comment]
@rtyler What do you think?  You can test this with:
```sh
 bundle exec rake strings:generate
firefox doc/index.html
```

**Comment by rtyler** [comment]
*shrug*

I'm indifferent

**Comment by jhoblitt** [comment]
I filed a couple of feature requests while slogging through that.

https://tickets.puppetlabs.com/browse/PDOC-157
https://tickets.puppetlabs.com/browse/PDOC-158

I was hoping for a CI mechanism to catch new params without docs.

**Comment by jhoblitt** [comment]
In any event, I'd at least like to merge the markup changes as I've add missing params and added/fixed up examples.

**Pull request merged**
