### PR TITLE
Dependency correction when manage_slave_user is false

### PR DESCRIPTION
**Pull request by james-powis**
Corrected Slave Dependency with when manage_slave_user is false and manage_client_jar is true

### CODE REVIEW

**Comment by jhoblitt** [comment]
So now that I actually think about it, this will have essentialy the same problem... I think what we need to do is have a conditional that declares the relationship when both  `$manage_slave_user  and if `$manage_client_jar` are true.  What do you think?

**Comment by james-powis** [comment]
the way I have gotten around this in the past has been to conditionally declare the same resource twice:
`if $manage_slave_user
  if $manage_client_jar
    user {'jenkins-slave_user':
      ...
      before => Archive['get_swarm_client']
    }
  } else {
    user {'jenkins-slave_user':
      ...
    }
}
`
What are your thoughts on that?

**Comment by jhoblitt** [comment]
We can express this without having to duplicate the resource.  Something along the lines of (untested):

```
  if ($manage_slave_user and $manage_client_jar) {
    User['jenkins-slave_user']->
      Archive['get_swarm_client']
  }
```

**Comment by jhoblitt** [comment]
:+1: Looks good.  Thank you contributing!

**Pull request merged**
