### PR TITLE
Add support for conduit credentials

### PR DESCRIPTION
**Pull request by oc243**
These are needed for jenkins to integrate with the phabricator plugin.

### CODE REVIEW

**Comment by jhoblitt** [comment]
I'm not familiar with the conduit credential type.  Is this from the phabricator plugin?

**Comment by oc243** [comment]
Yes, conduit is the HTTP API for phabricator that has its own credentials type that is used by Uber's phabricator plugin for jenkins.

**Comment by oc243** [comment]
@jhoblitt the CI seems to be broken on master. I don't think that this PR  causes any regressions in CI. Any chance of a merge, pls :D

**Comment by oc243** [comment]
Hey @jhoblitt! Are you happy with this PR? If so, is there any chance of a merge pls?

**Comment by jhoblitt** [comment]
Sure ;)

**Pull request merged**
