### PR TITLE
Kludge around jenkins 2.x landing in the 'latest' repos

### PR DESCRIPTION
**Pull request by jhoblitt**
Related to #575

### CODE REVIEW

**Comment by matthewbarr** [comment]
+1

**Comment by rtyler** [comment]
@jhoblitt I wonder if the repo change for an existing installation would render this as a "major" (in semver terms) incompatible change.

**Comment by jhoblitt** [comment]
@rtyler Err, uh... I suppose it could cause a downgrade.  I would hope that it's not the case since presumably the latest 1.x package would obsolete the most recent lts 1.x package.

**Comment by jhoblitt** [comment]
The travis failure was in the beaker tests on el6/el7 and appear to be timing (non-package) related.

**Pull request merged**
