### PR TITLE
Adds workaround for GPG issue for RHEL5

### PR DESCRIPTION
**Pull request by petems**
The version of Yum on EL5 < doesn't support the Jenkins GPG key from Yum:

```
Traceback (most recent call last):
 File "/usr/bin/yum", line 29, in ?
   yummain.user_main(sys.argv[1:], exit_code=True)
 File "/usr/share/yum-cli/yummain.py", line 309, in user_main
   errcode = main(args)
 File "/usr/share/yum-cli/yummain.py", line 261, in main
   return_code = base.doTransaction()
 File "/usr/share/yum-cli/cli.py", line 410, in doTransaction
   if self.gpgsigcheck(downloadpkgs) != 0:
 File "/usr/share/yum-cli/cli.py", line 510, in gpgsigcheck
   self.getKeyForPackage(po, lambda x, y, z: self.userconfirm())
 File "/usr/lib/python2.4/site-packages/yum/__init__.py", line 3544, in
getKeyForPackage
   keys = self._retrievePublicKey(keyurl, repo)
 File "/usr/lib/python2.4/site-packages/yum/__init__.py", line 3509, in
_retrievePublicKey
   keys_info = misc.getgpgkeyinfo(rawkey, multiple=True)
 File "/usr/lib/python2.4/site-packages/yum/misc.py", line 375, in
getgpgkeyinfo
   raise ValueError(str(e)) ValueError: unknown pgp packet type 17 at 706
```

This is a fix for that.

More detail here if interested:
http://dan.carley.co/blog/2012/05/22/yum-gpg-keys-for-jenkins/
https://groups.google.com/forum/?fromgroups#!topic/puppet-users/Yxiekm0j1J4
http://serverfault.com/questions/382158/installing-jenkins-with-puppet-fails-to-import-gpg-key

### CODE REVIEW

**Comment by jhoblitt** [comment]
That error gives me a giant frowny face...

**Comment by jhoblitt** [comment]
@petems I have 3 or 4 small modules using `stschulte/rpmkey` to import keys.  It uses a native provider instead of an exec and I haven't had any idempotentcy (sp?) issues with it.  E.g., https://github.com/jhoblitt/puppet-bluejeans/blob/master/manifests/repo.pp#L10-L13

**Comment by petems** [comment]
@jhoblitt Hmm, should we bring in an entire new module and dependancy for just one thing? I'm cool if so, I just feel like this is the easier one :+1:

**Comment by petems** [comment]
Moved to https://github.com/jenkinsci/puppet-jenkins/pull/346

**Pull request closed without merging**
