### PR TITLE
Add param disableClientsUniqueId

### PR DESCRIPTION
**Pull request by xdexter**
Adds the ability to set the parameter "disableClientsUniqueId".

### CODE REVIEW

**Comment by jhoblitt** [comment]
@xdexter I suspect the travis failure was caused by jenkins 2.x, which this module isn't yet compatible with.  Could you rebase on the current master?

**Comment by xdexter** [comment]
Hello @jhoblitt, excuse my delay.

I clone the repo with current master and apply changes, all works correctly!

Att;

**Comment by xdexter** [comment]
@jhoblitt

**Comment by jhoblitt** [comment]
@xdexter This PR needs to be rebased.

**Comment by jhoblitt** [comment]
This functionality was added via #719

**Comment by xdexter** [comment]
Hello @jhoblitt, thank you!

**Pull request closed without merging**
