### PR TITLE
add firewall module as a dependency

### PR DESCRIPTION
**Pull request by cristi1979**
also fix versions: x.y is not a valid version, x.y.z. is (according to gepetto)

### CODE REVIEW

**Comment by rtyler** [comment]
@matthewbarr if I remember correctly we explicitly decided against this dependency correct?

**Comment by jchristi** [comment]
Please don't add this. Some organizations like mine have their own custom firewall module (for better or for worse).  Adding this dependency would result in a namespace conflict.

**Comment by rtyler** [comment]
@christ66 I'm going to close this, I'm in agreement with @jchristi and our previous decision regarding keeping the puppetlabs-firewall dependency optional.

**Comment by christ66** [comment]
@rtyler I think you mean @cristi1979 :smile:

**Comment by matthewbarr** [comment]
Yep, explicitly not added :)

**Pull request closed without merging**
