### PR TITLE
assorted gem updates, cleanups, and/or removals

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
@rtyler Are you still using the blimpy configs?  This PR has a commit that removes them.

**Comment by rtyler** [comment]
@jhoblitt nah, let's burninate them

**Comment by jhoblitt** [comment]
ack - just need to figure out why rubocop is blowing up on puppet 3.8... or we just drop puppet 3.x...

**Comment by jhoblitt** [comment]
@rtyler The rubocop problem appears to be caused by puppet 3.x monkey patching YAML... instead of downgrading rubocop I did some `Rakefile` hackery to keep it skip running it against puppet 3.

**Pull request merged**
