### PR TITLE
fix acceptance test path prefix for jenkins-cli.jar

### PR DESCRIPTION
**Pull request by jhoblitt**
/usr/share/ -> /usr/lib/

### CODE REVIEW

**Comment by rtyler** [comment]
:+1:

**Comment by rtyler** [comment]
@jhoblitt Looks good to me, I've added you as a developer on this project so you should be able to merge this when it's green.

Let's meet up at puppetconf :)

**Comment by jhoblitt** [comment]
@rtyler Fantastic -- will do.

Are you attending the contributor summit? I'm flying into PDX tomorrow late in the afternoon.

**Comment by jhoblitt** [comment]
Look like my repo collab status hasn't taken effect yet.  I'll try again in a bit.

**Comment by rtyler** [comment]
Huh, the bot should have done that pretty much immediately. I'll take a look

**Comment by jhoblitt** [comment]
Still no dice.

**Pull request merged**
