### PR TITLE
#574 allow newline before start of private key

### PR DESCRIPTION
**Pull request by br0ch0n**
This is a fix/sortof workaround for #574 

I discovered by accident that if you pad your SSH private key with a newline, the CLI helper accepts it as an argument.  Problem is that it gets added as a file path rather than direct input since startsWith doesn't handle the leading newline (but at least it gets added as SOMETHING rather than throwing an arg error).  This change sorts that out. 

P.S. I know we should be using the native types instead but I was getting puppet_x load errors when I tried it  (on 3.8, not 4+) so I went back to this.

### CODE REVIEW

**Comment by jhoblitt** [comment]
The acceptance tests failed -- this might be because of jenkins 2.x.  I've restarted travis.  If it fails again, could you rebase on the current master?

**Comment by br0ch0n** [comment]
@jhoblitt yaa, I think master hasn't been building for awhile now: https://travis-ci.org/jenkinsci/puppet-jenkins/builds and is still red today, so I don't know that rebasing would help yet?

**Comment by jhoblitt** [comment]
There have been stability issues with the docker based acceptance tests that come and go with the phases of them moon.  I don't really understand the issue -- I am getting close to marking them as allowed to fail.

**Comment by br0ch0n** [comment]
went and rebased just for fun but tests have failed as expected.  Unless I missed it, I don't see any mention of using the LTS repo in the spec so I think you are testing against Jenkins 2.x as you mentioned earlier(which isn't supposed to work for whatever reason)?

**Comment by br0ch0n** [comment]
any update on this one?  If it helps, I've now been using it in prod for a few months now :D

**Comment by jhoblitt** [comment]
@br0ch0n Would you be willing to rebase on the current master to see if travis will pass?

**Comment by GuitarrasDeAmor** [comment]
Any updates on this?

**Pull request closed without merging**
