### PR TITLE
feature/remove jenkins plugin before downloading it

### PR DESCRIPTION
**Pull request by pouete**
## Why ?
This Pull request assess a problem when upgrading jenkins plugins : The module correctly check if the version is correct and if not, runs into the installation process.
However. as puppet-archive is used and is idempotent, it does not change the version of the so called plugin if it is already installed.

## How ?
The pull request is fairly simple : remove the previous file using exec.
If we use the file puppet method, 
```
file{"${::jenkins::plugin_dir}/${plugin}":
    ensure => absent
}
 
```
the file is already taken care of, and this leads to an error.

### CODE REVIEW

**Comment by SpencerMalone** [comment]
This definitely needs a merge, if possible. Tested it, and it works well. Here's an issue from 2015 describing this very behavior that never got followed up on: https://github.com/jenkinsci/puppet-jenkins/issues/445

**Comment by jhoblitt** [comment]
This seems reasonable but needs rspec coverage before it can be merged.

**Comment by pouete** [comment]
M, looks like the none passing tests are related to a problem with puppet-java ( puppet 4 <-> puppet 3.8 incompatibililty ?

**Comment by jhoblitt** [comment]
Thank you for contributing.  Rebased and merged as #792

**Pull request closed without merging**
