### PR TITLE
remove puppet > 3 < 3.6 from travis matrix

### PR DESCRIPTION
**Pull request by jhoblitt**
To reduce wall clock CI execution time.

### CODE REVIEW

**Comment by rtyler** [comment]
I don't think that Puppet 2.7 should be removed from the matrix. There's still lots of folks out there who haven't made the jump to 3 and I'd like to make sure we still support them.

**Comment by jhoblitt** [comment]
2.7 is completely excluded from the matrix as it is only compatible with ruby 1.8.7.  As is, its just dead configuration.

**Comment by rtyler** [comment]
Huh, I hadn't realized that. I suppose I'll have to add 1.8.7/2.7 in a later commit to support all my EoL buddies out there :P

**Comment by jhoblitt** [comment]
I'll drop that commit from the PR momentarily.

**Comment by jhoblitt** [comment]
Its gone.

**Pull request merged**
