### PR TITLE
use puppet/archive for all file downloads

### LINKED ISSUE #427: puppet module conflict with camptocamp/archive
Hi,

  We're running into an issue w/ module namespace conflict on camptocamp/archive.  We use puppetcommunity/archive.

  Has anyone run into this?  How have you worked around it?

### LINKED ISSUE #505: Jenkins::Slave/Exec[get_swarm_client] is not idempotent
We experienced this issue this morning, where the Jenkins download server must have been experiencing issues, and returned a 502 during the download; the next puppet run did not appear to attempt download the jar again, and manual intervention was required.

### PR DESCRIPTION
**Pull request by jhoblitt**
Replaces the use of:

- `camptocamp/archive`
- `nanliu/staging`
- `exec` resources using `wget` or `curl`

closes #340 (supersedes)
resolves #427
closes #433 (supersedes)
resolves #505
possibly related to #512

### CODE REVIEW

**Comment by jhoblitt** [comment]
I think I've found an issue that needs to be fixed before this is ready-to-merge.

**Comment by jhoblitt** [comment]
make that two problems...

**Comment by jhoblitt** [comment]
one fixed... at least one to go...

**Comment by jhoblitt** [comment]
@rtyler Assuming CI passes, this should be ready for merge.

**Comment by jhoblitt** [comment]
hmm, maybe not...

**Comment by jhoblitt** [comment]
I'm apparently bi-polar today.  This is working at least as well as it was before but the magic returning core plugins issue is still present.  It is ready for merge.

**Comment by rtyler** [comment]
I find this change to be agreeable.

**Pull request merged**
