### PR TITLE
cleanup existing plugin archive if extension changes

### LINKED ISSUE #512: jenkins::plugin ignores version changes
It appears that `jenkins::plugin` is incapable of updating an already installed plugin by changing it's version specification unless a checksum is specified.

This is the `archive::download` resource to download the plugin:

https://github.com/jenkinsci/puppet-jenkins/blob/532242964375efc1013ba186f201ecbd74de0b36/manifests/plugin.pp#L126-L140

which is includes an exec statement that will not run if the file already exists:

https://github.com/camptocamp/puppet-archive/blob/b535bb8011ee0dd221f618b4239ab05fb7db41ee/manifests/download.pp#L163

This may be related in #465

### PR DESCRIPTION
**Pull request by jhoblitt**
This PR is based on top of #516 and should be rebased after it is merged.

resolves #512
related to (but does not fix) #465

### CODE REVIEW

**Comment by jhoblitt** [comment]
@rtyler Help! Even with this PR, it is still not possible to update core plugins.  I have positively confirmed that the old plugin versions are being removed. Nuking the unpacked plugin dir doesn't seem to have any effect. Upon restart, jenkins will log errors about being until to load plugin classes and seems to put the original plugin version back (I assume they are bundled in the jar but I haven't run down the logic yet).  Any ideas?

```
==> master: Info: Computing checksum on file /var/lib/jenkins/plugins/credentials.jpi
==> master: Info: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.jpi]: Filebucketed /var/lib/jenkins/plugins/credentials.jpi to puppet with sum 7f6100d98bfb05780487f5a4172ec290
==> master: Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.jpi]/ensure: removed
==> master: Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/Archive[credentials.hpi]/ensure: download archive from https://updates.jenkins-ci.org/download/plugins/credentials/1.25/credentials.hpi to /var/lib/jenkins/plugins/credentials.hpi  without cleanup
==> master: Info: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/Archive[credentials.hpi]: Scheduling refresh of Service[jenkins]
==> master: Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/owner: owner changed 'root' to 'jenkins'
==> master: Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/group: group changed 'root' to 'jenkins'
==> master: Notice: /File[/var/lib/jenkins/plugins/credentials.hpi]/seluser: seluser changed 'unconfined_u' to 'system_u'
```

**Comment by jhoblitt** [comment]
It looks like the chef folks have also wrestled with this: https://github.com/chef-cookbooks/jenkins/issues/122#issuecomment-136900605

**Comment by jhoblitt** [comment]
Sounds like they are silently pinned... https://wiki.jenkins-ci.org/display/JENKINS/Pinned+Plugins Grrrr.

**Comment by jhoblitt** [comment]
pinning seems to work for everything but `credentials` but I think I've just run install the latest version requiring `icon-shim`.

**Comment by jhoblitt** [comment]
Oh, if you install via the update center, jenkins seems to download `credentials.hpi` and rename it to `credentails.jpi`.  Sheesh.

**Comment by jhoblitt** [comment]
Rebased on master after the merge of #516

**Comment by rtyler** [comment]
@jhoblitt Pinning AFAIK goes away in 2.0, I might need to ask @daniel-beck to confirm that though

**Comment by jhoblitt** [comment]
@rtyler - Ack - hopefully extra files in the plugin dir won't cause breakage.  We may need to add a fact for the jenkins core version so we can make the behavior conditional.

**Pull request merged**
