### PR TITLE
Remove quotes for fsroot as it breaks paths in Darwin

### PR DESCRIPTION
**Pull request by bond-os**
Tested on osx 10.11. When quotes are used, fsroot env variable is broken (eg. `/opt/jenkins'/opt/jenkins/'jenkins` instead of just `/opt/jenkins`

### CODE REVIEW

**Comment by jhoblitt** [comment]
That sounds really odd.  Could you post an example of shell expansion behaving that way?

**Comment by bond-os** [comment]
When running with quotes:
`
31014   ??  R      0:03.61 /usr/bin/java -jar /opt/jenkins-home/swarm-client-2.1-jar-with-dependencies.jar -mode normal -executors 6 -username jenkins-slave -password xxx -master xxx -labels 'osx' -fsroot '/opt/jenkins-home' -disableSslVerification
`

result of job run:
```
Building remotely on xxx (swarm osx) in workspace /opt/jenkins-home/'/opt/jenkins-home'/workspace/test1
[test1] $ /bin/sh -xe /var/folders/j5/tw2bd0dj5qg58h7_5_7rxkfw00000w/T/hudson3073667717673464980.sh
+ echo '/opt/jenkins-home/'\''/opt/jenkins-home'\''/workspace/test1'
/opt/jenkins-home/'/opt/jenkins-home'/workspace/test1
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS
```

when running without quotes:
`
31077   ??  S      0:05.08 /usr/bin/java -jar /opt/jenkins-home/swarm-client-2.1-jar-with-dependencies.jar -mode normal -executors 6 -username jenkins-slave -password xxx -master xxx -labels 'osx' -fsroot /opt/jenkins-home -disableSslVerification
`

result of job run:
```
Building remotely on pc8290139.ad.gd-48ac2424 (swarm osx) in workspace /opt/jenkins-home/workspace/test1
[test1] $ /bin/sh -xe /var/folders/j5/tw2bd0dj5qg58h7_5_7rxkfw00000w/T/hudson3679603742063845044.sh
+ echo /opt/jenkins-home/workspace/test1
/opt/jenkins-home/workspace/test1
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS
```

**Comment by rtyler** [comment]
@jhoblitt Perhaps it would be best to remove the quotes and use the `shellescape` method (or whatever it's called)

**Comment by jhoblitt** [comment]
This should be resolved by #719

**Pull request closed without merging**
