### PR TITLE
Support multiple swarm client args 

### PR DESCRIPTION
**Pull request by alvin-huang**
My desire was to use the -disableClientUniqueId option similar to #567. I thought it may be better to just create a long string for users to input multiple swarm client arguments. The list of options are listed here: https://github.com/jenkinsci/swarm-plugin/blob/master/client/src/main/java/hudson/plugins/swarm/Options.java.

There are quite a number of options that aren't implemented into the module currently and ultimately, I think this would be an easier way to do it than to add class parameters for each option. 

Thoughts?

### CODE REVIEW

**Comment by jhoblitt** [comment]
Could you add some rspec coverage of this change and rebase on current master?

**Comment by alvin-huang** [comment]
@jhoblitt Rebased and rspec tests added.

**Comment by jhoblitt** [comment]
Resolved by #665

**Comment by alvin-huang** [comment]
@jhoblitt you mean #655 :)

**Pull request closed without merging**
