### PR TITLE
Refactor acceptance tests to use beaker-rspec

### PR DESCRIPTION
**Pull request by petems**
Allows much easier tuning of tests, but still has serverspec so we can port over the existing tests. Beaker also has AWS support, so it's easy to test there too! :+1:

### CODE REVIEW

**Comment by rtyler** [comment]
Interesting work @petems! I'll try to make sure I review this over the weekend, post haste!

**Comment by petems** [comment]
Cool :) I'll probably add a line to the README.md about how to run it, but the tl;dr is:

Setup vagrant and virtualbox, then:

```
bundle exec rspec spec/acceptance/class_spec.rb
```

Whats _really_ cool is that beaker has docker support, so you can run acceptance tests in CI pretty easily without having to wait for the VM's to spin up (example here: https://app.wercker.com/#buildstep/542851191dfdddeb6b023822).

**Comment by rtyler** [comment]
@petems you're on the hook for adding a README update in another pull request. if I don't see it soon I'll have to beat it out of you at FOSDEM :)

**Comment by petems** [comment]
@rtyler Haha, I'll see what I can do! :)

**Pull request merged**
