### PR TITLE
Fix all require statements for files in puppet_x

### PR DESCRIPTION
**Pull request by vStone**
See: https://tickets.puppetlabs.com/browse/SERVER-973 for more
information

### CODE REVIEW

**Comment by jhoblitt** [comment]
@vStone Thank you for working on this.  Is is possible to use `require_relative` instead of duplicating the path mangling?

**Comment by vStone** [comment]
Done :)

**Comment by jhoblitt** [comment]
Could you rebase on the current master?  Hopefully that will get the rspec tests passing.

**Comment by vStone** [comment]
Also done :)

**Comment by vStone** [comment]
@jhoblitt Can we fast-track this pull request a bit so it doesn't end up in the never ending backlog.

**Comment by jhoblitt** [comment]
This looks good -- thank you for dealing with this.  The travis failure is the the ongoing "remoting" problem so I'm going to merge it.

**Pull request merged**
