### PR TITLE
Removing 'enable' statement on job.pp and job/present.pp

### PR DESCRIPTION
**Pull request by zonArt**
Removing 'enable' statement on job.pp and job/present.pp which are breaking idempotence

### CODE REVIEW

**Comment by jhoblitt** [comment]
@zonart I confess to being a bit torn because I would like to see this feature removed.  However, I think we can't remove the parameter without a major API bump. 

@jenkinsci/puppet-jenkins-developers how would you feel about making this param a no-op and adding a warning?

**Comment by zonArt** [comment]
@jhoblitt I made it a no-op with warning as you suggested, I agree that this is a better compromise

**Comment by jhoblitt** [comment]
@jenkinsci/puppet-jenkins-developers Could one of the other maintainers ack this PR?  I am in favor of this change because the feature, as implemented, is inherently non-indempotent and fragile as there is no semantic parsing of the xstream dump.

**Comment by zonArt** [comment]
Any news on this one ? Is it possible to get it merge ?

**Comment by edomaur** [comment]
:+1:  if we can merge it soon it would be really nice

**Comment by cClaude** [comment]
continuous-integration/travis-ci/pr — The Travis CI build failed

Seem to be link to a docker issue, not related to this PR.

**Comment by cClaude** [comment]
+1

**Comment by zonArt** [comment]
Tests are fixed, parameter has been set as deprecated, backward compatibility is not broken as feared at first commits, what else is missing? If there are any concerns remaining, please tell so that I can propose something

**Comment by pouete** [comment]
+1

**Comment by elconas** [comment]
Do you do semantic versioning for this puppet module ? If so, I think this breaks users as it changes behaviour and needs a major version change. 

In our case we rely on this feature to create disabled jobs and let the build manager decide when and when to run it as this job, bootstraps a whole CI Pipeline with JobDSL (we added seed_only option as shown in https://github.com/jenkinsci/puppet-jenkins/pull/500).

So with the current implementation, behaviour changes silently (ok a warning, but no failure). I would rather see a failure to force the admin to look into it and break no assumptions.

**Pull request merged**
