### PR TITLE
Fix compatibility with apt module

### PR DESCRIPTION
**Pull request by skolekonov**
- key_source parameter was removed, key parameter should be used instead.
- include_src was also removed and set to false by default, there's no need to
  override it anymore.

### CODE REVIEW

**Comment by jhoblitt** [comment]
This will likely require updating the fixtures, metadata.json, and some spec tests.

**Comment by bleuchtang** [comment]
I fix lints and tests issues here: https://github.com/bleuchtang/puppet-jenkins/tree/puppetjenkins_PR_281 .
@skolekonov can you rebase my branch please ?

**Comment by cypherfox** [comment]
@bleuchtang: I have deployed your changes, and they work fine. Could you please create new pull request? 
I have tried #301, but it has it's own problems.

**Comment by bleuchtang** [comment]
@cypherfox: done here: #321

**Comment by jhoblitt** [comment]
#323 has been merged; this PR can be closed out. /cc @rtyler

**Pull request closed without merging**
